/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ComparatorsAndDate.Datum;
import Majetok.DruhMajetku;
import Majetok.Majetok;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class PridajMajetokGUI extends javax.swing.JDialog {
    private Majetok m;
    /**
     * Creates new form pridajMajetok
     */
    public PridajMajetokGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.datumObstarania.setText(Datum.formatDatum(Calendar.getInstance()));
        this.m = null;
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datumObstarania = new javax.swing.JTextField();
        nazov = new javax.swing.JTextField();
        vyrobca = new javax.swing.JTextField();
        cena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        druhMajetku = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        pridajMajetok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridaj majetok");

        jLabel1.setText("Názov");

        jLabel2.setText("Cena");

        jLabel3.setText("Dátum obstarania");

        jLabel4.setText("Výrobca");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Zadajte údaje o majetku");

        druhMajetku.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Krátkodobý", "Dlhodobý" }));

        jLabel6.setText("Druh majetku");

        pridajMajetok.setText("Pridaj majetok");
        pridajMajetok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajMajetokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cena, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(datumObstarania, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(nazov, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(vyrobca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(druhMajetku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(pridajMajetok))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumObstarania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vyrobca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(druhMajetku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(pridajMajetok)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajMajetokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajMajetokActionPerformed

        try {
            String nazovM = this.nazov.getText();
            String vyrobcaM = this.vyrobca.getText();
            double cenaM = Double.parseDouble(this.cena.getText());
            DruhMajetku druhM;
            if (this.druhMajetku.getSelectedIndex() == 0) {
                druhM = DruhMajetku.kratkodoby;
            } else {
                druhM = DruhMajetku.dlhodoby;
            }
            Calendar datumM = Datum.parseDatum(this.datumObstarania.getText());
            m = new Majetok(nazovM, cenaM, druhM, datumM, vyrobcaM);
            dispose();
        } catch (ParseException | IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
 
    }//GEN-LAST:event_pridajMajetokActionPerformed

    public Majetok getMajetok() {
        return m;
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cena;
    private javax.swing.JTextField datumObstarania;
    private javax.swing.JComboBox druhMajetku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nazov;
    private javax.swing.JButton pridajMajetok;
    private javax.swing.JTextField vyrobca;
    // End of variables declaration//GEN-END:variables
}
