/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Doklady.PFA;
import Doklady.Predkontacia;
import Partneri.Partner;
import Partneri.ZoznamPartnerov;
import RamcovaUctovaOsnova.RamcovaUctovaOsnova;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tomáš
 */
public class PridajPFAGUI extends javax.swing.JDialog {
    private List<Predkontacia> predkontacie;
    private PFA pfa = null;
    private RamcovaUctovaOsnova ruo;
    private ZoznamPartnerov zp;
    private Partner partner;


    /**
     * Creates new form PridajIDGUI
     */
    public PridajPFAGUI(java.awt.Frame parent, boolean modal, RamcovaUctovaOsnova ruo, ZoznamPartnerov zp) {
        super(parent, modal);
        initComponents();
        this.predkontacie = new ArrayList<>();
        this.ruo = ruo;
        Calendar d = Calendar.getInstance();
        this.datumVytvoreniaDokladu.setText(ComparatorsAndDate.Datum.formatDatum(d));
        this.celkovaHodnotaDokladu.setText("0.0 €");
        this.zp = zp;
        this.partner = null;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datumVytvoreniaDokladu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vyberPartnera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        celkovaHodnotaDokladu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        znenieDokladu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabulka = new javax.swing.JTable();
        pridajPredkontaciu = new javax.swing.JButton();
        odstranPredkontaciu = new javax.swing.JButton();
        zauctujID = new javax.swing.JButton();
        partnerPopis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        externeCislo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridaj došlú faktúru");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Zadajte informácie o prijatej faktúre");

        jLabel2.setText("Dátum vytvorenia dokladu");

        jLabel3.setText("Partner");

        vyberPartnera.setText("Vyber partnera");
        vyberPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberPartneraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Celková hodnota dokladu");

        celkovaHodnotaDokladu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        celkovaHodnotaDokladu.setText("  ");

        jLabel6.setText("Znenie dokladu");

        tabulka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Znenie predkontácie", "MD", "D", "Suma"
            }
        ));
        jScrollPane1.setViewportView(tabulka);

        pridajPredkontaciu.setText("Pridaj predkontáciu");
        pridajPredkontaciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajPredkontaciuActionPerformed(evt);
            }
        });

        odstranPredkontaciu.setText("Odstráň predkontáciu");
        odstranPredkontaciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranPredkontaciuActionPerformed(evt);
            }
        });

        zauctujID.setText("Zaúčtuj prijatú faktúru");
        zauctujID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zauctujIDActionPerformed(evt);
            }
        });

        partnerPopis.setText("Nie je vybraný žiadny partner");

        jLabel5.setText("Externé číslo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(znenieDokladu)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vyberPartnera, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(datumVytvoreniaDokladu)
                                            .addComponent(partnerPopis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(47, 47, 47)
                                        .addComponent(celkovaHodnotaDokladu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(externeCislo))
                                        .addComponent(odstranPredkontaciu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(pridajPredkontaciu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 52, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(zauctujID)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(datumVytvoreniaDokladu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(externeCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(partnerPopis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vyberPartnera)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridajPredkontaciu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(odstranPredkontaciu)
                        .addGap(25, 25, 25)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znenieDokladu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(celkovaHodnotaDokladu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(zauctujID)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajPredkontaciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajPredkontaciuActionPerformed
        PridajPredkontaciuGUI pp = new PridajPredkontaciuGUI(null, true, ruo);
        if (pp.getPredkontacia() != null) {
            this.predkontacie.add(pp.getPredkontacia());
            this.obnovUdaje();
        }
    }//GEN-LAST:event_pridajPredkontaciuActionPerformed

    private void odstranPredkontaciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranPredkontaciuActionPerformed
        try {
            int i = this.tabulka.getSelectedRow();
            this.predkontacie.remove(i);
            this.obnovUdaje();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nie je vybraná predkontácia");
        }


    }//GEN-LAST:event_odstranPredkontaciuActionPerformed

    private void zauctujIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zauctujIDActionPerformed
        try {
            String nazovDokladu = this.znenieDokladu.getText();
            Calendar datum = ComparatorsAndDate.Datum.parseDatum(this.datumVytvoreniaDokladu.getText());
            double hodnota = 0;
            for (Predkontacia p : this.predkontacie) {
                hodnota += p.getSuma();
            }
            int ecislo = Integer.parseInt(this.externeCislo.getText());
            this.pfa = new PFA(nazovDokladu, datum, hodnota, this.partner, this.predkontacie, ecislo);
            dispose();
        } catch (ParseException | IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_zauctujIDActionPerformed

    public PFA getPfa() {
        return pfa;
    }

    private void vyberPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberPartneraActionPerformed
        VyberPartneraGUI vp = new VyberPartneraGUI(null, true, zp);
        if (vp.getParent() != null) {
            this.partner = vp.getPartner();
            this.partnerPopis.setText(this.partner.getMeno());
        }

    }//GEN-LAST:event_vyberPartneraActionPerformed

    public void obnovUdaje() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Znenie predkontácie");
        model.addColumn("MD");
        model.addColumn("D");
        model.addColumn("Suma");
        double suma = 0;
        for (Predkontacia p : this.predkontacie) {
            model.addRow(new Object[] {p.getZnenie(), p.getStranaMD().getCisloUctu(), p.getStranaD().getCisloUctu(), p.getSumaString()});
            suma += p.getSuma();
        }
        String sumaDokladu = String.valueOf(suma) + " €"; 
        this.tabulka.setModel(model);
        this.celkovaHodnotaDokladu.setText(sumaDokladu);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celkovaHodnotaDokladu;
    private javax.swing.JTextField datumVytvoreniaDokladu;
    private javax.swing.JTextField externeCislo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton odstranPredkontaciu;
    private javax.swing.JLabel partnerPopis;
    private javax.swing.JButton pridajPredkontaciu;
    private javax.swing.JTable tabulka;
    private javax.swing.JButton vyberPartnera;
    private javax.swing.JButton zauctujID;
    private javax.swing.JTextField znenieDokladu;
    // End of variables declaration//GEN-END:variables
}
