/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Doklady.Predkontacia;
import GUI.VyberUcetGUI;
import RamcovaUctovaOsnova.RamcovaUctovaOsnova;
import RamcovaUctovaOsnova.Ucet;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class PridajPredkontaciuGUI extends javax.swing.JDialog {
    private Predkontacia predkontacia;
    private Ucet stranaMD;
    private Ucet stranaD;
    private RamcovaUctovaOsnova ruo;
    /**
     * Creates new form PridajPredkontaciuGUI
     */
    public PridajPredkontaciuGUI(java.awt.Frame parent, boolean modal, RamcovaUctovaOsnova ruo) {
        super(parent, modal);
        initComponents();
        this.ruo = ruo;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        znenie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ruoMD = new javax.swing.JButton();
        ruoD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        suma = new javax.swing.JTextField();
        vytvorPredkontaciu = new javax.swing.JButton();
        md = new javax.swing.JLabel();
        d = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridaj predkontáciu");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Zadajte informácie o predkontácii");

        jLabel2.setText("Znenie");

        jLabel3.setText("Predkontácia");

        jLabel4.setText("MD");

        jLabel5.setText("D");

        ruoMD.setText("...");
        ruoMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruoMDActionPerformed(evt);
            }
        });

        ruoD.setText("...");
        ruoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruoDActionPerformed(evt);
            }
        });

        jLabel6.setText("Suma");

        vytvorPredkontaciu.setText("Vytvor predkontáciu");
        vytvorPredkontaciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorPredkontaciuActionPerformed(evt);
            }
        });

        md.setText("Nie je vybraný účet");

        d.setText("Nie je vybraný účet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(znenie, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(md)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ruoMD, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ruoD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(vytvorPredkontaciu)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(znenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruoMD)
                    .addComponent(md))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d)
                    .addComponent(ruoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(vytvorPredkontaciu)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruoMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruoMDActionPerformed
        VyberUcetGUI mdgui = new VyberUcetGUI(null, true, ruo);
        this.stranaMD = mdgui.getUcet();
        this.md.setText(stranaMD.getCisloUctu());
    }//GEN-LAST:event_ruoMDActionPerformed

    private void ruoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruoDActionPerformed
        VyberUcetGUI dgui = new VyberUcetGUI(null, true, ruo);
        this.stranaD = dgui.getUcet();
        this.d.setText(stranaD.getCisloUctu());
    }//GEN-LAST:event_ruoDActionPerformed

    private void vytvorPredkontaciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorPredkontaciuActionPerformed

        try {
            String nazov = this.znenie.getText();
            double sumaa = Double.parseDouble(this.suma.getText());
            this.predkontacia = new Predkontacia(this.stranaMD, this.stranaD, sumaa, nazov);
            dispose();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_vytvorPredkontaciuActionPerformed

    public Predkontacia getPredkontacia() {
        return predkontacia;
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel md;
    private javax.swing.JButton ruoD;
    private javax.swing.JButton ruoMD;
    private javax.swing.JTextField suma;
    private javax.swing.JButton vytvorPredkontaciu;
    private javax.swing.JTextField znenie;
    // End of variables declaration//GEN-END:variables
}
