/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import RamcovaUctovaOsnova.RamcovaUctovaOsnova;
import Sklad.PolozkaSkladu;
import Sklad.Prijemka;
import Sklad.Sklad;
import Sklad.ZoznamSkladovychKariet;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class PridajPrijemkuGUI extends javax.swing.JDialog {
    private Prijemka prijemka;
    private Prijemka prijemkaPom = null;
    private Sklad sklad;
    private ZoznamSkladovychKariet zoznamSK;
    private DefaultListModel<PolozkaSkladu> dlm;
    /**
     * Creates new form PridajPrijemkuGUID
     */
    public PridajPrijemkuGUI(java.awt.Frame parent, boolean modal,Sklad s, ZoznamSkladovychKariet zsk, RamcovaUctovaOsnova ruo) {
        super(parent, modal);
        initComponents();
        this.sklad = s;
        Calendar d = Calendar.getInstance();
        this.datumVytvorenia.setText(ComparatorsAndDate.Datum.formatDatum(d));
        this.prijemkaPom = new Prijemka(sklad, d, ruo);
        this.zoznamSK = zsk;
        this.setLocationRelativeTo(this);
        this.dlm = new DefaultListModel<>();
        this.vypis.setModel(dlm);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        celkovaHodnota = new javax.swing.JLabel();
        datumVytvorenia = new javax.swing.JTextField();
        nazov = new javax.swing.JLabel();
        cena = new javax.swing.JLabel();
        mnozstvo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pridajPolozku = new javax.swing.JButton();
        vytvorPrijemku = new javax.swing.JButton();
        odstranPolozku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridaj príjemku");

        vypis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypis);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o položke");

        jLabel2.setText("Názov");

        jLabel3.setText("Cena");

        jLabel4.setText("Množstvo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Celková hodnota príjemky");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Dátum vytvorenia príjemky");

        celkovaHodnota.setText("   ");

        datumVytvorenia.setText("jTextField1");

        nazov.setText("   ");

        cena.setText("   ");

        mnozstvo.setText("   ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ponuka činností");

        pridajPolozku.setText("Pridaj položku");
        pridajPolozku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajPolozkuActionPerformed(evt);
            }
        });

        vytvorPrijemku.setText("Vytvor príjemku");
        vytvorPrijemku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorPrijemkuActionPerformed(evt);
            }
        });

        odstranPolozku.setText("Odstráň položku");
        odstranPolozku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranPolozkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(celkovaHodnota, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datumVytvorenia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nazov, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(cena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mnozstvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odstranPolozku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pridajPolozku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vytvorPrijemku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nazov))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mnozstvo))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(celkovaHodnota))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(datumVytvorenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20)
                        .addComponent(pridajPolozku)
                        .addGap(7, 7, 7)
                        .addComponent(odstranPolozku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vytvorPrijemku))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisValueChanged
        PolozkaSkladu selected = (PolozkaSkladu)this.vypis.getSelectedValue();
        if (selected != null) {
            this.cena.setText(selected.getSkladovaKarta().getCenaString());
            this.nazov.setText(selected.getSkladovaKarta().getNazov());
            this.mnozstvo.setText(String.valueOf(selected.getPocetKs()));
            this.celkovaHodnota.setText(this.prijemkaPom.celkovaSumaString());
        } 
    }//GEN-LAST:event_vypisValueChanged

    private void vytvorPrijemkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorPrijemkuActionPerformed
        try {
            Calendar d = ComparatorsAndDate.Datum.parseDatum(this.datumVytvorenia.getText());
            this.prijemkaPom.setDatumVytvorenia(d);
            this.prijemka = prijemkaPom;
            dispose();
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(rootPane, "Je zadaný zlý dátum");
        }      
    }//GEN-LAST:event_vytvorPrijemkuActionPerformed

    private void pridajPolozkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajPolozkuActionPerformed
        VyberSkladovuKartuGUI vskgui = new VyberSkladovuKartuGUI(null, true, zoznamSK, sklad);
        if (vskgui.getSelected() != null) {
            this.prijemkaPom.pridajPolozkuDoDokladu(vskgui.getSelected());
            this.obnovZoznam();  
        }
    }//GEN-LAST:event_pridajPolozkuActionPerformed

    private void odstranPolozkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranPolozkuActionPerformed
        PolozkaSkladu selected = (PolozkaSkladu)this.vypis.getSelectedValue();
        if (selected != null) {
            int i = JOptionPane.showConfirmDialog(rootPane, "Naozaj chcete odstrániť túto položku z dokladu?", "Odstránenie položky", JOptionPane.YES_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                this.prijemkaPom.odoberPolozkuZDokladu(selected);
                this.obnovZoznam();  
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvolená položka");
        }
    }//GEN-LAST:event_odstranPolozkuActionPerformed
    public void obnovZoznam() {
        DefaultListModel<PolozkaSkladu> dlmnew = new DefaultListModel<>();
        for (PolozkaSkladu p : (ArrayList<PolozkaSkladu>)this.prijemkaPom.getPolozkyDokladu()) {
            dlmnew.addElement(p);
        }
        this.vypis.setModel(dlmnew);
    }

    public Prijemka getPrijemka() {
        return prijemka;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celkovaHodnota;
    private javax.swing.JLabel cena;
    private javax.swing.JTextField datumVytvorenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mnozstvo;
    private javax.swing.JLabel nazov;
    private javax.swing.JButton odstranPolozku;
    private javax.swing.JButton pridajPolozku;
    private javax.swing.JList vypis;
    private javax.swing.JButton vytvorPrijemku;
    // End of variables declaration//GEN-END:variables
}
