/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ComparatorsAndDate.CisloUctuMaxComparator;
import ComparatorsAndDate.CisloUctuMinComparator;
import ComparatorsAndDate.NazovUctuAZComparator;
import ComparatorsAndDate.NazovUctuZAComparator;
import RamcovaUctovaOsnova.Aktiv;
import RamcovaUctovaOsnova.Nakladovy;
import RamcovaUctovaOsnova.Pasiv;
import RamcovaUctovaOsnova.RamcovaUctovaOsnova;
import RamcovaUctovaOsnova.Ucet;
import RamcovaUctovaOsnova.Vynosovy;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class RuoGUI extends javax.swing.JFrame {
    private RamcovaUctovaOsnova ruo;
    private DefaultListModel<Ucet> dlm = new DefaultListModel<>();
    private Ucet ucet;
//    private JLabel druhUctu = null;
    /**
     * Creates new form RuoGUI
     */;
    /**
     * Creates new form RuoGUI
     */
    public RuoGUI(RamcovaUctovaOsnova paRuo) {
        initComponents();
        this.ruo = paRuo;
        for (Ucet u : ruo.getRamcovaUctovnaOsnova()) {
            dlm.addElement(u);
        }
        this.vypis.setModel(dlm); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JList();
        popis1 = new javax.swing.JLabel();
        druhUctu = new javax.swing.JLabel();
        popis2 = new javax.swing.JLabel();
        jeDanovy = new javax.swing.JLabel();
        sortovanie = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cisloUctu = new javax.swing.JLabel();
        nazovUctu = new javax.swing.JLabel();
        danovost = new javax.swing.JComboBox();
        nastavDanovost = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rámcová účtová osnova");

        vypis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vypis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypis);

        popis1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        popis1.setText("Informácie o účte");

        druhUctu.setText(" ");

        popis2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        popis2.setText("Triedenie");

        jeDanovy.setText(" ");

        sortovanie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Podľa čísla účtu vzostupne", "Podľa čísla účtu zostupne", "Podľa názvu účtu vzostupne", "Podľa názvu účtu zostupne" }));
        sortovanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortovanieActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nastavenie daňovosti pre zvolený účet");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Číslo účtu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Názov účtu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Typ účtu");

        cisloUctu.setText(" ");

        nazovUctu.setText(" ");

        danovost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daňový účet", "Nedaňový účet" }));

        nastavDanovost.setText("Nastav");
        nastavDanovost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastavDanovostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(nastavDanovost))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(popis2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(popis1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(danovost, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazovUctu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cisloUctu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jeDanovy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(druhUctu, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(popis1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cisloUctu)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazovUctu)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(druhUctu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jeDanovy)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(danovost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nastavDanovost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(popis2)
                        .addGap(12, 12, 12)
                        .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortovanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortovanieActionPerformed
        if (this.sortovanie.getSelectedIndex() == 0) {
            ruo.zoradRUOPodlaCislaUctuMin();
            this.obnovZoznam();
        } else if (this.sortovanie.getSelectedIndex() == 1) {
            ruo.zoradRUOPodlaCislaUctuMax();
            this.obnovZoznam();
        } else if (this.sortovanie.getSelectedIndex() == 2) {
            ruo.zoradRUOPodlaNazvuUctuAZ();
            this.obnovZoznam(); 
        } else if (this.sortovanie.getSelectedIndex() == 3) {
            ruo.zoradRUOPodlaNazvuUctuZA();
            this.obnovZoznam();
        }
    }//GEN-LAST:event_sortovanieActionPerformed

    private void vypisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisValueChanged
        Ucet selected = (Ucet)this.vypis.getSelectedValue();
        if (selected != null) {
            if (selected instanceof Aktiv) {
                this.druhUctu.setText("Účet: Aktív");
            } else if (selected instanceof Pasiv) {
                this.druhUctu.setText("Účet: Pasív");
            } else if (selected instanceof Nakladovy) {
                this.druhUctu.setText("Účet: Nákladový");
            } else if (selected instanceof Vynosovy) {
                this.druhUctu.setText("Účet: Výnosový");
            }
            this.cisloUctu.setText(selected.getCisloUctu());
            this.nazovUctu.setText(selected.getNazovUctu());
            if (selected.isDanovyUcet()) {
                this.jeDanovy.setText("Daňový účet");
            } else {
                this.jeDanovy.setText("Nedaňový účet");
            }
        }
    }//GEN-LAST:event_vypisValueChanged

    private void nastavDanovostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastavDanovostActionPerformed
        Ucet pom = (Ucet)this.vypis.getSelectedValue();
        if (pom != null) {
            Ucet u = this.ruo.getUcetPodlaCisla(pom.getCisloUctu());
            if (this.danovost.getSelectedIndex() == 0) {
                u.setDanovyUcet(true);
                JOptionPane.showMessageDialog(rootPane, "Účet je odteraz daňový");
                this.obnovZoznam();
            } else if (this.danovost.getSelectedIndex() == 1) {
                u.setDanovyUcet(false);
                JOptionPane.showMessageDialog(rootPane, "Účet je odteraz nedaňový");
                this.obnovZoznam();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvolený účet");
        }
    }//GEN-LAST:event_nastavDanovostActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public void obnovZoznam() {
        DefaultListModel<Ucet> dlmnew = new DefaultListModel<>();
        for (Ucet u : ruo.getRamcovaUctovnaOsnova()) {
            dlmnew.addElement(u);
        }
        this.dlm = dlmnew;
        this.vypis.setModel(dlm);
    }
    

        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cisloUctu;
    private javax.swing.JComboBox danovost;
    private javax.swing.JLabel druhUctu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jeDanovy;
    private javax.swing.JButton nastavDanovost;
    private javax.swing.JLabel nazovUctu;
    private javax.swing.JLabel popis1;
    private javax.swing.JLabel popis2;
    private javax.swing.JComboBox sortovanie;
    private javax.swing.JList vypis;
    // End of variables declaration//GEN-END:variables

}
