/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Partneri.Partner;
import Partneri.ZoznamPartnerov;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class VyberPartneraGUI extends javax.swing.JDialog {
    private ZoznamPartnerov zp;
    private DefaultListModel<Partner> dlm;
    private Partner partner = null;
    /**
     * Creates new form VyberPartneraGUI
     */
    public VyberPartneraGUI(java.awt.Frame parent, boolean modal, ZoznamPartnerov paZp) {
        super(parent, modal);
        initComponents();
        this.zp = paZp;
        this.dlm = new DefaultListModel<>();
        for (Partner p : this.zp.getPartneri()) {
            dlm.addElement(p);
        }
        this.vypisPartnerov.setModel(dlm);
        this.setResizable(false);        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vypisPartnerov = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pridajPartnera = new javax.swing.JButton();
        odoberPartnera = new javax.swing.JButton();
        vyberParntera = new javax.swing.JButton();
        meno = new javax.swing.JLabel();
        adresa = new javax.swing.JLabel();
        ico = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyber partnera");

        vypisPartnerov.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisPartnerovValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypisPartnerov);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o partnerovi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Meno");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Adresa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("IČO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Štát");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ponuka činností");

        pridajPartnera.setText("Pridaj parntera");
        pridajPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajPartneraActionPerformed(evt);
            }
        });

        odoberPartnera.setText("Odober partnera");
        odoberPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odoberPartneraActionPerformed(evt);
            }
        });

        vyberParntera.setText("Vyber partnera");
        vyberParntera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberParnteraActionPerformed(evt);
            }
        });

        meno.setText("   ");

        adresa.setText("   ");

        ico.setText("   ");

        stat.setText("   ");

        id.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(meno, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(adresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vyberParntera)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(odoberPartnera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pridajPartnera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(meno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(adresa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ico))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(stat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(id))
                        .addGap(52, 52, 52)
                        .addComponent(vyberParntera)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(pridajPartnera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(odoberPartnera)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypisPartnerovValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisPartnerovValueChanged
        Partner p = (Partner)this.vypisPartnerov.getSelectedValue();
        if (p != null) {
            this.adresa.setText(p.getAdresa());
            this.ico.setText(String.valueOf(p.getICO()));
            this.id.setText(String.valueOf(p.getId()));
            this.meno.setText(p.getMeno());
            this.stat.setText(p.getStat());
        }
    }//GEN-LAST:event_vypisPartnerovValueChanged

    private void pridajPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajPartneraActionPerformed
        PridajPartneraGUI pp = new PridajPartneraGUI(null, true);
        try {
            this.zp.pridajPartnera(pp.getPartner());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.obnovZoznam();
    }//GEN-LAST:event_pridajPartneraActionPerformed

    private void odoberPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odoberPartneraActionPerformed
                                              
        int s = JOptionPane.showConfirmDialog(rootPane, "Naozaj chcete vymazať tohto partnera?", "Odstránenie partnera", JOptionPane.YES_NO_OPTION);
        if (s == JOptionPane.YES_NO_OPTION) {
            this.zp.odstranParntera((Partner)this.vypisPartnerov.getSelectedValue());
            this.obnovZoznam();
        }
    }//GEN-LAST:event_odoberPartneraActionPerformed

    private void vyberParnteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberParnteraActionPerformed
        Partner p = (Partner)this.vypisPartnerov.getSelectedValue();
        if (p != null) {
            this.partner = p;
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvolený partner");
        }
    }//GEN-LAST:event_vyberParnteraActionPerformed

    public void obnovZoznam() {
        DefaultListModel<Partner> dlmnew = new DefaultListModel<>();
        for (Partner p : this.zp.getPartneri()) {
            dlmnew.addElement(p);
        }
        this.dlm = dlmnew;
        this.vypisPartnerov.setModel(dlm);
    }

    public Partner getPartner() {
        return partner;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresa;
    private javax.swing.JLabel ico;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel meno;
    private javax.swing.JButton odoberPartnera;
    private javax.swing.JButton pridajPartnera;
    private javax.swing.JLabel stat;
    private javax.swing.JButton vyberParntera;
    private javax.swing.JList vypisPartnerov;
    // End of variables declaration//GEN-END:variables
}
