/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ComparatorsAndDate.Datum;
import Sklad.PolozkaSkladu;
import Sklad.Sklad;
import Sklad.SkladovaKarta;
import Sklad.ZoznamSkladovychKariet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class VyberSkladovuKartuGUI extends javax.swing.JDialog {
    private ZoznamSkladovychKariet zoznamSK;
    private DefaultListModel<SkladovaKarta> dlm;
    private Sklad sklad;
    private PolozkaSkladu selected;
    /**
     * Creates new form VyberSkladovuKartuGUI
     */
    public VyberSkladovuKartuGUI(java.awt.Frame parent, boolean modal, ZoznamSkladovychKariet zsk, Sklad sklad) {
        super(parent, modal);
        initComponents();
        this.zoznamSK = zsk;
        this.dlm = new DefaultListModel<>();
        for (SkladovaKarta s : this.zoznamSK.getZoznamSkladovychKariet()) {
            this.dlm.addElement(s);
        }
        this.vypis.setModel(dlm);
        this.setLocationRelativeTo(null);
        this.sklad = sklad;
        this.setResizable(false);
        this.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pocet = new javax.swing.JTextField();
        pridajDoDokladu = new javax.swing.JButton();
        pridajSkladovuKartu = new javax.swing.JButton();
        odstranSK = new javax.swing.JButton();
        nazov = new javax.swing.JLabel();
        cena = new javax.swing.JLabel();
        datum = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        mnozstvo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyber skladovú kartu");

        vypis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vypis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypis);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o skladovej karte");

        jLabel2.setText("Názov");

        jLabel3.setText("Cena");

        jLabel4.setText("Dátum zaradenia");

        jLabel5.setText("ID");

        jLabel6.setText("Množstvo na sklade");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Zadajte množstvo, ktoré chcete pridať do dokladu");

        pridajDoDokladu.setText("Pridaj do dokladu");
        pridajDoDokladu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajDoDokladuActionPerformed(evt);
            }
        });

        pridajSkladovuKartu.setText("Pridaj skladovú kartu");
        pridajSkladovuKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajSkladovuKartuActionPerformed(evt);
            }
        });

        odstranSK.setText("Odstraň skladovú kartu");
        odstranSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranSKActionPerformed(evt);
            }
        });

        nazov.setText("   ");

        cena.setText("   ");

        datum.setText("   ");

        id.setText("   ");

        mnozstvo.setText("   ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ponuka činností");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(pridajDoDokladu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odstranSK)
                            .addComponent(pridajSkladovuKartu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(pocet, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nazov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mnozstvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nazov))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(datum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(mnozstvo))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pocet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pridajDoDokladu)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(pridajSkladovuKartu)
                        .addGap(18, 18, 18)
                        .addComponent(odstranSK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void pridajSkladovuKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajSkladovuKartuActionPerformed
        PridajSkladovuKartuGUI psk = new PridajSkladovuKartuGUI(null, true);
        if (psk.getSk() != null) {
            if (!this.zoznamSK.pridajSkladovuKartu(psk.getSk())) {
                JOptionPane.showMessageDialog(null, "Skladovu kartu sa nepodarilo pridat. Skuste to znovu");
            } else {
                JOptionPane.showMessageDialog(null, "Skladova karta bola uspesne pridata");
            }
            this.obnovList();
        }
    }//GEN-LAST:event_pridajSkladovuKartuActionPerformed

    private void pridajDoDokladuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajDoDokladuActionPerformed
        SkladovaKarta pom = (SkladovaKarta)this.vypis.getSelectedValue();
        if (pom == null) {
            JOptionPane.showMessageDialog(this, "Nevybrali ste si skladovú kartu");
        } else {
            try {
            int pocet = Integer.parseInt(this.pocet.getText());
            this.selected = new PolozkaSkladu(pom, pocet);
            dispose();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Zadali ste nesprávne údaje");
            }  
        }

    }//GEN-LAST:event_pridajDoDokladuActionPerformed

    private void vypisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisValueChanged
        SkladovaKarta sk = (SkladovaKarta)this.vypis.getSelectedValue();
        if (sk != null) {
            this.nazov.setText(sk.getNazov());
            this.cena.setText(sk.getCenaString());
            this.datum.setText(Datum.formatDatum(sk.getDatumZaradenia()));
            this.id.setText(String.valueOf(sk.getIdTovaru()));
            this.mnozstvo.setText(String.valueOf(this.sklad.dajPocetKusovPodlaId(sk.getIdTovaru())));
        }
    }//GEN-LAST:event_vypisValueChanged

    private void odstranSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranSKActionPerformed
        SkladovaKarta selected = (SkladovaKarta) this.vypis.getSelectedValue();
        if (selected != null) {
            int i = JOptionPane.showConfirmDialog(rootPane, "Naozaj chcete odstrániť skladovú kartu?", "Odstránenie skladovej karty", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
                this.zoznamSK.odstranSkladovuKartu(selected);
                this.obnovList();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvolená skladová karta");
        }
    }//GEN-LAST:event_odstranSKActionPerformed

    public void obnovList() {
        DefaultListModel<SkladovaKarta> dlmnew = new DefaultListModel<>();
         for (SkladovaKarta s : this.zoznamSK.getZoznamSkladovychKariet()) {
            dlmnew.addElement(s);
        }
        this.vypis.setModel(dlmnew);
    }

    public PolozkaSkladu getSelected() {
        return selected;
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cena;
    private javax.swing.JLabel datum;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mnozstvo;
    private javax.swing.JLabel nazov;
    private javax.swing.JButton odstranSK;
    private javax.swing.JTextField pocet;
    private javax.swing.JButton pridajDoDokladu;
    private javax.swing.JButton pridajSkladovuKartu;
    private javax.swing.JList vypis;
    // End of variables declaration//GEN-END:variables
}
