/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import RamcovaUctovaOsnova.Aktiv;
import RamcovaUctovaOsnova.Nakladovy;
import RamcovaUctovaOsnova.Pasiv;
import RamcovaUctovaOsnova.RamcovaUctovaOsnova;
import RamcovaUctovaOsnova.Ucet;
import RamcovaUctovaOsnova.Vynosovy;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class VyberUcetGUI extends javax.swing.JDialog {
    private Ucet ucet;
    private RamcovaUctovaOsnova ruo;
    private DefaultListModel<Ucet> dlm = new DefaultListModel<>();
    /**
     * Creates new form VyberUcetGUI
     */
    public VyberUcetGUI(java.awt.Frame parent, boolean modal, RamcovaUctovaOsnova paRuo) {
        super(parent, modal);
        initComponents();
        this.ruo = paRuo;
        for (Ucet u : ruo.getRamcovaUctovnaOsnova()) {
            dlm.addElement(u);
        }
        this.vypis.setModel(dlm);       
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cisloUctu = new javax.swing.JLabel();
        nazovUctu = new javax.swing.JLabel();
        druhUctu = new javax.swing.JLabel();
        jeDanovy = new javax.swing.JLabel();
        vyberUcet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vyber účet");

        vypis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vypis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypis);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o účte");

        jLabel2.setText("Číslo účtu");

        jLabel3.setText("Názov účtu");

        jLabel4.setText("Typ účtu");

        cisloUctu.setText(" ");

        nazovUctu.setText(" ");

        druhUctu.setText(" ");

        jeDanovy.setText(" ");

        vyberUcet.setText("Vyber účet");
        vyberUcet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberUcetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cisloUctu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nazovUctu, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                    .addComponent(druhUctu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jeDanovy, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(vyberUcet)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cisloUctu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nazovUctu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(druhUctu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jeDanovy)
                        .addGap(18, 18, 18)
                        .addComponent(vyberUcet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisValueChanged
        Ucet selected = (Ucet)this.vypis.getSelectedValue();
        if (selected != null) {
            if (selected instanceof Aktiv) {
                this.druhUctu.setText("Účet: Aktív");
            } else if (selected instanceof Pasiv) {
                this.druhUctu.setText("Účet: Pasív");
            } else if (selected instanceof Nakladovy) {
                this.druhUctu.setText("Účet: Nákladový");
            } else if (selected instanceof Vynosovy) {
                this.druhUctu.setText("Účet: Výnosový");
            }
            this.cisloUctu.setText(selected.getCisloUctu());
            this.nazovUctu.setText(selected.getNazovUctu());
            if (selected.isDanovyUcet()) {
                this.jeDanovy.setText("Daňový účet");
            } else {
                this.jeDanovy.setText("Nedaňový účet");
            }
        }
    }//GEN-LAST:event_vypisValueChanged

    private void vyberUcetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberUcetActionPerformed
        Ucet selected = (Ucet)this.vypis.getSelectedValue();
        if (selected != null) {
            this.ucet = selected;
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvoleny ucet");
        }
    }//GEN-LAST:event_vyberUcetActionPerformed

    public Ucet getUcet() {
        return ucet;
    }

    /**
     * @param args the command line arguments
     */
    public void obnovZoznam() {
        DefaultListModel<Ucet> dlmnew = new DefaultListModel<>();
        for (Ucet u : ruo.getRamcovaUctovnaOsnova()) {
            dlmnew.addElement(u);
        }
        this.dlm = dlmnew;
        this.vypis.setModel(dlm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cisloUctu;
    private javax.swing.JLabel druhUctu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jeDanovy;
    private javax.swing.JLabel nazovUctu;
    private javax.swing.JButton vyberUcet;
    private javax.swing.JList vypis;
    // End of variables declaration//GEN-END:variables
}
