/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ComparatorsAndDate.MenoPartneraAZComparator;
import ComparatorsAndDate.MenoPartneraZAComparator;
import Partneri.Partner;
import Partneri.ZoznamPartnerov;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class ZoznamPartnerovGUI extends javax.swing.JFrame {
    private ZoznamPartnerov zp;
    private DefaultListModel<Partner> dlm;
    /**
     * Creates new form ZoznamPartnerovGUI
     */
    public ZoznamPartnerovGUI(ZoznamPartnerov paZp) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.zp = paZp;
        this.dlm = new DefaultListModel<>();
        for (Partner p : this.zp.getPartneri()) {
            dlm.addElement(p);
        }
        this.vypisPartnerov.setModel(dlm);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vypisPartnerov = new javax.swing.JList();
        pridajPartnera = new javax.swing.JButton();
        odoberPartnera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        meno = new javax.swing.JLabel();
        adresa = new javax.swing.JLabel();
        ico = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sortovanie = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zoznam partnerov");

        vypisPartnerov.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisPartnerovValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vypisPartnerov);

        pridajPartnera.setText("Pridaj partnera");
        pridajPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajPartneraActionPerformed(evt);
            }
        });

        odoberPartnera.setText("Odober parntera");
        odoberPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odoberPartneraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o partnerovi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Meno");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Adresa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("IČO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Štát");

        meno.setText(" ");

        adresa.setText(" ");

        ico.setText(" ");

        stat.setText(" ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ID");

        id.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ponuka činností");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Triedenie");

        sortovanie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Podľa mena partnera vzostupne", "Podľa mena partnera zostupne" }));
        sortovanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortovanieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(87, 87, 87)
                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(69, 69, 69)
                                        .addComponent(meno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ico, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(52, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pridajPartnera, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odoberPartnera))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(meno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(adresa))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ico))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(stat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(id))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pridajPartnera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(odoberPartnera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajPartneraActionPerformed(java.awt.event.ActionEvent evt) throws IllegalArgumentException {//GEN-FIRST:event_pridajPartneraActionPerformed
        PridajPartneraGUI pp = new PridajPartneraGUI(this, true);
        try {
            this.zp.pridajPartnera(pp.getPartner());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.obnovZoznam();
    }//GEN-LAST:event_pridajPartneraActionPerformed

    private void vypisPartnerovValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisPartnerovValueChanged
        Partner p = (Partner)this.vypisPartnerov.getSelectedValue();
        if (p != null) {
            this.adresa.setText(p.getAdresa());
            this.ico.setText(String.valueOf(p.getICO()));
            this.id.setText(String.valueOf(p.getId()));
            this.meno.setText(p.getMeno());
            this.stat.setText(p.getStat());
        }
    }//GEN-LAST:event_vypisPartnerovValueChanged

    private void odoberPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odoberPartneraActionPerformed
        int s = JOptionPane.showConfirmDialog(rootPane, "Naozaj chcete vymazať tohto partnera?", "Odstránenie partnera", JOptionPane.YES_NO_OPTION);
        if (s == JOptionPane.YES_NO_OPTION) {
            this.zp.odstranParntera((Partner)this.vypisPartnerov.getSelectedValue());
            this.obnovZoznam();
        }
    }//GEN-LAST:event_odoberPartneraActionPerformed

    private void sortovanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortovanieActionPerformed
        if (this.sortovanie.getSelectedIndex() == 0) {
            this.zp.zoradPartnerovPodlaMenaAZ();
            this.obnovZoznam();
        } else if (this.sortovanie.getSelectedIndex() == 1) {
            this.zp.zoradPartnerovPodlaMenaZA();
            this.obnovZoznam();
        }
    }//GEN-LAST:event_sortovanieActionPerformed

    public void obnovZoznam() {
        DefaultListModel<Partner> dlmnew = new DefaultListModel<>();
        for (Partner p : this.zp.getPartneri()) {
            dlmnew.addElement(p);
        }
        this.dlm = dlmnew;
        this.vypisPartnerov.setModel(dlm);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresa;
    private javax.swing.JLabel ico;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel meno;
    private javax.swing.JButton odoberPartnera;
    private javax.swing.JButton pridajPartnera;
    private javax.swing.JComboBox sortovanie;
    private javax.swing.JLabel stat;
    private javax.swing.JList vypisPartnerov;
    // End of variables declaration//GEN-END:variables
}
