/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ComparatorsAndDate.NazovMajetkuAZComparator;
import ComparatorsAndDate.NazovMajetkuZAComparator;
import ComparatorsAndDate.Datum;
import Majetok.DruhMajetku;
import Majetok.Majetok;
import Majetok.ZoznamMajetku;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class ZoznamMajetkuGUI extends javax.swing.JFrame {
    private ZoznamMajetku zm = null;
    private DefaultListModel<Majetok> dlm;
    /**
     * Creates new form GUI
     */
    public ZoznamMajetkuGUI(ZoznamMajetku paZm) {
        initComponents();
        this.zm = paZm;
        this.dlm = new DefaultListModel<>();
        for (Majetok m : this.zm.getZoznamMajetku()) {
            this.dlm.addElement(m);
        }
        this.vypis.setModel(dlm);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JList();
        pridajMajetok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nazov = new javax.swing.JLabel();
        cena = new javax.swing.JLabel();
        vyrobca = new javax.swing.JLabel();
        datum = new javax.swing.JLabel();
        druh = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        odoberMajetok = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sortovanie = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zoznam majetku");

        vypis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vypis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vypisValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(vypis);

        pridajMajetok.setText("Pridaj majetok");
        pridajMajetok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajMajetokActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informácie o majetku");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Názov");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Obstarávacia cena");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Výrobca");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dátum obstarania");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Druh majetku");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ID Majetku");

        nazov.setText(" ");

        cena.setText(" ");

        vyrobca.setText(" ");

        datum.setText(" ");

        druh.setText(" ");

        id.setText(" ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ponuka činností");

        odoberMajetok.setText("Odober majetok");
        odoberMajetok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odoberMajetokActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Triedenie");

        sortovanie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Podľa názvu majetku vzostupne", "Podľa názvu majetku zostupne" }));
        sortovanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortovanieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nazov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vyrobca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(datum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(druh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pridajMajetok, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(odoberMajetok, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nazov))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cena))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vyrobca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(datum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(druh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(id))
                        .addGap(63, 63, 63)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(pridajMajetok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(odoberMajetok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19)
                        .addComponent(sortovanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vypisValueChanged
        Majetok m = (Majetok)this.vypis.getSelectedValue();
        if (m != null) {
            String cenam = String.valueOf(m.getCena()) + " €";
            this.cena.setText(cenam);
            this.nazov.setText(m.getNazov());
            this.vyrobca.setText(m.getVyrobca());
            this.datum.setText(Datum.formatDatum(m.getDatum()));
            this.id.setText(String.valueOf(m.getIdMajetku()));
            if (m.getTyp() == DruhMajetku.dlhodoby) {
                this.druh.setText("Dlhodobý majetok");
            } else {
                this.druh.setText("Krátkodobý majetok");
            }
        }
    }//GEN-LAST:event_vypisValueChanged

    private void pridajMajetokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajMajetokActionPerformed
        PridajMajetokGUI pm = new PridajMajetokGUI(this, true);
        if (pm.getMajetok() != null) {
            this.zm.pridajMajetok(pm.getMajetok());
            JOptionPane.showMessageDialog(this, "Majetok bol pridaný");           
        }
        this.obnovZoznam();
    }//GEN-LAST:event_pridajMajetokActionPerformed

    private void sortovanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortovanieActionPerformed
        if (this.sortovanie.getSelectedIndex() == 0) {
            this.zm.zoradMajetokPodlaNazvuAZ();
            this.obnovZoznam(); 
        } else if (this.sortovanie.getSelectedIndex() == 1) {
            this.zm.zoradMajetokPodlaNazvuZA();
            this.obnovZoznam();
        }
    }//GEN-LAST:event_sortovanieActionPerformed

    private void odoberMajetokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odoberMajetokActionPerformed
        Majetok m = (Majetok)this.vypis.getSelectedValue();
        if (m != null) {
            int i = JOptionPane.showConfirmDialog(rootPane, "Naozaj chcete odstrániť tento majetok?", "Odobratie majetku", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
                zm.odoberMajetok(m);
                JOptionPane.showMessageDialog(rootPane, "Majetok bol odstránený");
                this.obnovZoznam();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nie je zvolený majetok");
        }
    }//GEN-LAST:event_odoberMajetokActionPerformed

    private void obnovZoznam() {
        DefaultListModel<Majetok> dlmnew = new DefaultListModel<>();
        for (Majetok m : this.zm.getZoznamMajetku()) {
            dlmnew.addElement(m);
        }
        this.dlm = dlmnew;
        this.vypis.setModel(dlm);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cena;
    private javax.swing.JLabel datum;
    private javax.swing.JLabel druh;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nazov;
    private javax.swing.JButton odoberMajetok;
    private javax.swing.JButton pridajMajetok;
    private javax.swing.JComboBox sortovanie;
    private javax.swing.JList vypis;
    private javax.swing.JLabel vyrobca;
    // End of variables declaration//GEN-END:variables
}
